sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
    
install:
  - npm install haxeshim -g
  - npm install switchx -g
  - switchx download
  - haxe switchx.hxml
  - npm install . -g
  - switchx install

script:

  - switchx list