sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
    
install:
  - npm install haxeshim -g
  - npm install lix.pm -g
  - lix download
  - haxe switchx.hxml
  - npm install . -g

script:

  - switchx list