sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
    
install:
  - npm install haxe-travix lix.pm haxeshim -g
  - lix download
  - haxe switchx.hxml
  - npm install . -g

script:
  - travix neko